package web591

// Generated by https://quicktype.io

type HomeDetail struct {
	Data   HomeDetailData `json:"data"`
	Msg    string         `json:"msg"`
	Status int64          `json:"status"`
}

type HomeDetailData struct {
	Breadcrumb    []Breadcrumb  `json:"breadcrumb"` // [0] 縣市資料 [1] 區資料 [2] 住家類型資料
	Browse        Browse        `json:"browse"`
	CostData      CostData      `json:"costData"` // 租金外費用資料
	DealText      string        `json:"dealText"`
	DealTime      int64         `json:"dealTime"`
	Deposit       string        `json:"deposit"`
	FavData       FavData       `json:"favData"` // 租用單位簡介
	HouseDetail   HouseDetail   `json:"houseDetail"`
	Info          []Info        `json:"info"` // 租任單位格局資訊
	InfoData      InfoData      `json:"infoData"`
	Kind          int64         `json:"kind"`
	LinkInfo      LinkInfo      `json:"linkInfo"`
	NavData       []HouseDetail `json:"navData"`
	PositionRound PositionRound `json:"positionRound"`
	Preference    CostData      `json:"preference"`
	Price         string        `json:"price"` // 租金
	PriceCache    []interface{} `json:"priceCache"`
	PriceCacheTxt string        `json:"priceCacheTxt"`
	PriceUnit     string        `json:"priceUnit"` // 租金單位
	Publish       Publish       `json:"publish"`
	QuestionData  HouseDetail   `json:"questionData"`
	RegionID      int64         `json:"regionId"`
	Relieved      int64         `json:"relieved"`
	Remark        HouseDetail   `json:"remark"`
	Rooms         HouseDetail   `json:"rooms"`
	SectionID     int64         `json:"sectionId"`
	Service       Service       `json:"service"`
	ShareInfo     ShareInfo     `json:"shareInfo"`
	Tags          []Tag         `json:"tags"`
	Title         string        `json:"title"`
}

// 租金
func (h *HomeDetailData) GetPrice() string {
	return h.Price
}

// 租任時間限制
func (h *HomeDetailData) GetDesc() string {
	return h.Service.Desc
}

// 租任規則
func (h *HomeDetailData) GetRule() string {
	return h.Service.Rule
}

// 地址
func (h *HomeDetailData) GetAddress() string {
	return h.PositionRound.Address
}

// 縣市資料
func (h *HomeDetailData) GetRegion() string {
	for _, info := range h.Breadcrumb {
		if info.Query == "region" {
			return info.Name
		}
	}

	return ""
}

// 市區資料
func (h *HomeDetailData) GetSection() string {
	for _, info := range h.Breadcrumb {
		if info.Query == "section" {
			return info.Name
		}
	}

	return ""
}

// 押金
func (h *HomeDetailData) GetDeposit() string {
	for _, info := range h.CostData.Data {
		if info.Key == "deposit" {
			return info.Value
		}
	}

	return ""
}

// 管理費
func (h *HomeDetailData) GetManageprice() string {
	for _, info := range h.CostData.Data {
		if info.Key == "manageprice" && info.Value != "無" {
			return info.Value
		}
	}

	return ""
}

// 住宅 格局
func (h *HomeDetailData) GetLayout() string {
	for _, info := range h.Info {
		if info.Key == "layout" {
			return info.Value
		}
	}

	return ""
}

// 住宅 坪數
func (h *HomeDetailData) GetArea() string {
	for _, info := range h.Info {
		if info.Key == "area" {
			return info.Value
		}
	}

	return ""
}

// 住宅 樓層
func (h *HomeDetailData) GetFloor() string {
	for _, info := range h.Info {
		if info.Key == "floor" {
			return info.Value
		}
	}

	return ""
}

// 住宅 型態
func (h *HomeDetailData) GetShape() string {
	for _, info := range h.Info {
		if info.Key == "shape" {
			return info.Value
		}
	}

	return ""
}

// 住家類型名稱
func (h *HomeDetailData) Getkind() string {
	for _, info := range h.Breadcrumb {
		if info.Query == "kind" {
			return info.Name
		}
	}

	return ""
}

type Breadcrumb struct {
	ID    int64  `json:"id"`
	Link  string `json:"link"`
	Name  string `json:"name"`
	Query string `json:"query"`
}

type Browse struct {
	Mobile int64 `json:"mobile"`
	PC     int64 `json:"pc"`
}

type CostData struct { // 租用成本
	Active   int64   `json:"active"`
	Data     []Info  `json:"data"`
	Title    string  `json:"title"`
	Footnote *string `json:"footnote,omitempty"`
}

type Info struct {
	Key   string `json:"key"` // deposit: 押金, manageprice: 管理費
	Name  string `json:"name"`
	Value string `json:"value"`
}

type FavData struct {
	Address  string `json:"address"` //地址
	Area     string `json:"area"`    // 坪數
	Count    int64  `json:"count"`
	KindTxt  string `json:"kindTxt"`  // 住家類型名稱
	Layout   string `json:"layout"`   // 租任單位格局
	Posttime int64  `json:"posttime"` // 刊登時間
	Price    int64  `json:"price"`    // 價格
	Thumb    string `json:"thumb"`    // 縮圖
	Title    string `json:"title"`    // 刊登標題
}

type HouseDetail struct {
	Active  int64         `json:"active"`
	Key     string        `json:"key"`
	Title   string        `json:"title"`
	Content *string       `json:"content,omitempty"`
	Data    []interface{} `json:"data"`
}

type InfoData struct {
	Active         int64           `json:"active"`
	Data           []InfoDataDatum `json:"data"`
	HasCertificate int64           `json:"hasCertificate"`
	Title          string          `json:"title"`
}

type InfoDataDatum struct {
	Alias string `json:"alias"`
	Cate  int64  `json:"cate"`
	Key   string `json:"key"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

type LinkInfo struct {
	Avatar            string        `json:"avatar"`
	CertificateStatus int64         `json:"certificateStatus"`
	CertificateTxt    string        `json:"certificateTxt"`
	ChargeTxt         string        `json:"chargeTxt"`
	IMName            string        `json:"imName"`
	IMUid             int64         `json:"imUid"`
	IsTransferTel     int64         `json:"isTransferTel"`
	Line              string        `json:"line"`
	Mobile            string        `json:"mobile"`
	Name              string        `json:"name"`
	Phone             string        `json:"phone"`
	RentNum           int64         `json:"rentNum"`
	Role              int64         `json:"role"`
	RoleName          string        `json:"roleName"`
	RoleTxt           string        `json:"roleTxt"`
	SaleNum           int64         `json:"saleNum"`
	ShopID            int64         `json:"shopId"`
	ShopStatus        int64         `json:"shopStatus"`
	ShopVolume        int64         `json:"shopVolume"`
	SkillCases        []interface{} `json:"skillCases"`
	SkillWork         []interface{} `json:"skillWork"`
	Tips              string        `json:"tips"`
	Uid               int64         `json:"uid"`
	Warnmsg           int64         `json:"warnmsg"`
}

type PositionRound struct {
	Active        int64                `json:"active"`
	Address       string               `json:"address"`
	CommunityID   int64                `json:"communityId"`
	CommunityName string               `json:"communityName"`
	Data          []PositionRoundDatum `json:"data"`
	Key           string               `json:"key"`
	Lat           string               `json:"lat"`
	Lng           string               `json:"lng"`
	MapData       []MapDatum           `json:"mapData"`
	Title         string               `json:"title"`
}

type PositionRoundDatum struct {
	Children []DatumChild `json:"children"`
	Key      string       `json:"key"`
	Name     string       `json:"name"`
}

type DatumChild struct {
	Distance    int64  `json:"distance"`
	DistanceTxt string `json:"distanceTxt"`
	Name        string `json:"name"`
	Type        string `json:"type"`
}

type MapDatum struct {
	Children []MapDatumChild `json:"children"`
	Key      string          `json:"key"`
	Name     string          `json:"name"`
}

type MapDatumChild struct {
	Children []ChildChild `json:"children"`
	Key      string       `json:"key"`
	Name     string       `json:"name"`
}

type ChildChild struct {
	Distance            int64  `json:"distance"`
	Lat                 string `json:"lat"`
	Lng                 string `json:"lng"`
	Name                string `json:"name"`
	TradingAreaDistance int64  `json:"trading_area_distance"`
	TradingAreaID       int64  `json:"trading_area_id"`
}

type Publish struct {
	ID         int64  `json:"id"`
	Key        string `json:"key"`
	Name       string `json:"name"`
	PostTime   string `json:"postTime"`
	UpdateTime string `json:"updateTime"`
}

type Service struct {
	Active   int64      `json:"active"`
	Desc     string     `json:"desc"`
	Facility []Facility `json:"facility"`
	Key      string     `json:"key"`
	Rule     string     `json:"rule"`
	Title    string     `json:"title"`
}

type Facility struct {
	Active int64  `json:"active"`
	Key    string `json:"key"`
	Name   string `json:"name"`
}

type ShareInfo struct {
	From  string `json:"from"`
	Title string `json:"title"`
	URL   string `json:"url"`
}

type Tag struct {
	ID    int64  `json:"id"`
	Value string `json:"value"`
}
