// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: dtoschedule.proto

package dtoschedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Spec     string `protobuf:"bytes,2,opt,name=Spec,proto3" json:"Spec,omitempty"`
	CallBack string `protobuf:"bytes,3,opt,name=CallBack,proto3" json:"CallBack,omitempty"`
}

func (x *NewTaskReq) Reset() {
	*x = NewTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtoschedule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTaskReq) ProtoMessage() {}

func (x *NewTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_dtoschedule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTaskReq.ProtoReflect.Descriptor instead.
func (*NewTaskReq) Descriptor() ([]byte, []int) {
	return file_dtoschedule_proto_rawDescGZIP(), []int{0}
}

func (x *NewTaskReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewTaskReq) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *NewTaskReq) GetCallBack() string {
	if x != nil {
		return x.CallBack
	}
	return ""
}

type NewTaskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewTaskRes) Reset() {
	*x = NewTaskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dtoschedule_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTaskRes) ProtoMessage() {}

func (x *NewTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_dtoschedule_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTaskRes.ProtoReflect.Descriptor instead.
func (*NewTaskRes) Descriptor() ([]byte, []int) {
	return file_dtoschedule_proto_rawDescGZIP(), []int{1}
}

var File_dtoschedule_proto protoreflect.FileDescriptor

var file_dtoschedule_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x74, 0x6f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x74, 0x6f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x22, 0x50, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61,
	0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61,
	0x63, 0x6b, 0x22, 0x0c, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73,
	0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dtoschedule_proto_rawDescOnce sync.Once
	file_dtoschedule_proto_rawDescData = file_dtoschedule_proto_rawDesc
)

func file_dtoschedule_proto_rawDescGZIP() []byte {
	file_dtoschedule_proto_rawDescOnce.Do(func() {
		file_dtoschedule_proto_rawDescData = protoimpl.X.CompressGZIP(file_dtoschedule_proto_rawDescData)
	})
	return file_dtoschedule_proto_rawDescData
}

var file_dtoschedule_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dtoschedule_proto_goTypes = []interface{}{
	(*NewTaskReq)(nil), // 0: dtoschedule.NewTaskReq
	(*NewTaskRes)(nil), // 1: dtoschedule.NewTaskRes
}
var file_dtoschedule_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dtoschedule_proto_init() }
func file_dtoschedule_proto_init() {
	if File_dtoschedule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dtoschedule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dtoschedule_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTaskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dtoschedule_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dtoschedule_proto_goTypes,
		DependencyIndexes: file_dtoschedule_proto_depIdxs,
		MessageInfos:      file_dtoschedule_proto_msgTypes,
	}.Build()
	File_dtoschedule_proto = out.File
	file_dtoschedule_proto_rawDesc = nil
	file_dtoschedule_proto_goTypes = nil
	file_dtoschedule_proto_depIdxs = nil
}
